# Generated by Django 4.1 on 2022-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(db_column='ex_id', primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.CharField(db_column='ex_date', max_length=10, verbose_name='date')),
                ('time', models.CharField(db_column='ex_time', max_length=11, verbose_name='time')),
                ('room', models.CharField(db_column='ex_room', max_length=255, verbose_name='room')),
                ('department', models.CharField(db_column='ex_department', max_length=255, verbose_name='department')),
                ('professor', models.CharField(db_column='ex_professor', max_length=255, verbose_name='professor')),
                ('course', models.CharField(db_column='ex_course', max_length=255, verbose_name='course')),
                ('notes', models.TextField(db_column='ex_notes', verbose_name='notes')),
            ],
            options={
                'db_table': 'exams',
            },
        ),
    ]
