# Generated by Django 4.1 on 2022-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aueb_exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='professor',
            field=models.CharField(blank=True, db_column='ex_professor', max_length=255, null=True, verbose_name='professor'),
        ),
    ]
