# Generated by Django 4.1 on 2022-08-22 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aueb_exams', '0002_alter_exam_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.CharField(db_column='ex_date', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_date_format', message='Date must be of "DDMMYY" format.', regex='^([0-9][1-9]){2}[0-9]{4}$')], verbose_name='date'),
        ),
    ]
