# Generated by Django 4.1 on 2022-08-22 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aueb_exams', '0003_alter_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.CharField(db_column='ex_date', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_date_format', message='Date must be of "DD/MM/YYYY" format.', regex='^([0-9][1-9]\\/){2}[0-9]{4}$')], verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.CharField(db_column='ex_time', max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_time_format', message='Time must be of "HH:MM-HH:MM" format.', regex='^[0-9]{2}:[0-9]{2}-[0-9]{2}:[0-9]{2}$')], verbose_name='time'),
        ),
    ]
